stages:
- stage: del_rule
  jobs:
  - deployment: del_nsg_rule
    displayName: Remove inbound rule from controller nsg
    continueOnError: false
    environment: 'spoke14-kv'
    strategy:
        runOnce:
          deploy:
           steps:
             - task: AzureKeyVault@1
               inputs:
                 ConnectedServiceName: $(service_name)
                 KeyVaultName: $(key_vault_name)
                 SecretsFilter: '*'
                 RunAsPreJob: false 
             - task: AzureCLI@2
               inputs:
                  azureSubscription: 'atulavtx-sst2'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az network nsg rule delete --name deploy14 --nsg-name $(controller-nsg)  --resource-group $(controller-rg)'
