trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: spoke14-kv

stages:
- template: pipeline-templates/addnsg.yaml
- template: pipeline-templates/valandplan.yaml
- template: pipeline-templates/approval.yaml
- template: pipeline-templates/apply.yaml
- template: pipeline-templates/delnsg.yaml
